#!/bin/sh

NOTIFY_APP_NAME="screen warmness"

warmness() {
	[ -z "$1" ] && return 1

	case "$1" in
		"n")
			redshift -P -O 4500 && notify-send -a "$NOTIFY_APP_NAME" "enabled night mode"
			;;
		"d")
			redshift -P -O 6500 && notify-send -a "$NOTIFY_APP_NAME" "enabled light mode"
			;;
	esac
}

if [ -n "$1" ]; then
	warmness "$1"
else
	CHOICE=$(printf "1) night mode\n2) day mode" | rofi -dmenu -p "make the choice")

	case "$CHOICE" in
		"1)"*)
			warmness "n"
			;;
		"2)"*)
			warmness "d"
			;;
	esac
fi

# vim: ft=sh
