#!/bin/sh

CHOICE=$(printf "1) power off\n2) reboot\n3) lock\n4) log out" | rofi -dmenu -p "make the choice")

case "$CHOICE" in
	"1)"*)
		shutdown now
		;;
	"2)"*)
		reboot
		;;
	"3)"*)
		sleep 0.3; blurlock
		;;
	"4)"*)
		pkill -15 -U $USER
		;;
esac

# vim: ft=sh
