#!/bin/sh

#BUNDLEPATH="$HOME/nvim/bundle"
BUNDLEPATH="$HOME/Temp/bundle"

INFO_TITLE="Pathogen plugin enabler/disabler"

if [ ! "$(find "$BUNDLEPATH"/* -type d | wc -l)" -gt 0 ]; then
	zenity --no-wrap --info --title="$INFO_TITLE" --text="No plugin installed at $BUNDLEPATH directory"
	exit 1
fi

ENABLED=""
DISABLED=""

for folder in "$BUNDLEPATH"/*; do
	if [ "$(find "$folder" -type d | wc -l)" -eq 0 ]; then
		continue
	fi
	case "$folder" in
		*~)
			if [ "$DISABLED" = "" ]; then
				DISABLED="$folder"
			else
				DISABLED="$DISABLED $folder"
			fi
			;;
		*)
			if [ "$ENABLED" = "" ]; then
				ENABLED="$folder"
			else
				ENABLED="$ENABLED $folder"
			fi
			;;
	esac
done

ENABLED_BASENAME=""
DISABLED_BASENAME=""

for folder in $ENABLED; do
	folder_basename="$(basename "$folder")"
	if [ "$ENABLED_BASENAME" = "" ]; then
		ENABLED_BASENAME="$folder_basename"
	else
		ENABLED_BASENAME="$ENABLED_BASENAME $folder_basename"
	fi
done

for folder in $DISABLED; do
	folder_basename="$(basename "$folder")"
	if [ "$DISABLED_BASENAME" = "" ]; then
		DISABLED_BASENAME="$folder_basename"
	else
		DISABLED_BASENAME="$DISABLED_BASENAME $folder_basename"
	fi
done


if ! zenity --no-wrap --question --title="$INFO_TITLE" --text="Which plugins to list?" --ok-label="disabled" --cancel-label="enabled"; then # enabled
	ANS=$(zenity --list --title="$INFO_TITLE" --column="enabled plugins" $ENABLED_BASENAME)
	if [ "$ANS" = "" ]; then # nothing was selected
		exit 0
	fi
	if zenity --no-wrap --question --title="$INFO_TITLE" --text="Are you sure you want to disable $ANS plugin?"; then
		zenity --no-wrap --info --title="$INFO_TITLE" --text="Successfully disabled $ANS plugin"
		mv "$BUNDLEPATH/$ANS" "$BUNDLEPATH/$ANS~"
	fi
else # disabled
	ANS=$(zenity --list --title="$INFO_TITLE" --column="disabled plugins" $DISABLED_BASENAME)
	if [ "$ANS" = "" ]; then # nothing was selected
		exit 0
	fi
	if zenity --no-wrap --question --title="$INFO_TITLE" --text="Are you sure you want to enable $ANS plugin?"; then
		zenity --no-wrap --info --title="$INFO_TITLE" --text="Successfully enabled $ANS plugin"
	mv "$BUNDLEPATH/$ANS" "$BUNDLEPATH/${ANS%%?}"
	fi
fi

# vim: ft=sh
