#!/bin/sh

bspc rule -r "*"

cfg() {
	bspc config $@
}

cfg border_width 3
cfg window_gap 4
cfg top_padding 20

cfg normal_border_color  "#7197E7"
cfg active_border_color  "#7197E7"
cfg focused_border_color "#A77AC4"

cfg single_monocle true
cfg borderless_monocle true
cfg gapless_monocle true

cfg focus_follows_pointer true
cfg pointer_follows_focus false
cfg pointer_follows_monitor true

cfg remove_disabled_monitors true

desktops="1 2 3 4 5 6 7 8 9 10"

bspc monitor HDMI-A-0 -d $desktops
bspc monitor HDMI-A-1 -d $desktops
