[autostart]
exec = [
	"xsetroot -cursor_name left_ptr"
]

[settings]
	# Window settings
	gapSize = 12
	borderWidth = 2
	borderColorUnfocused = "#282C34"
	borderColorFocused = "#A77AC4"
	borderColorUrgent = "#E06C75"
	# Bar settings
	barHeight = 19
	windowTitlePosition = "left"
	barBackgroundColor = "#282C34"
	barForegroundColor = "#F8F8F2"
	barSelectionColor = "#A77AC4"
	barUrgentColor = "#E06C75"
	barFonts = [
		"JetBrains Mono:size=8:antialias=true",
		"Font Awesome 5 Free Solid:size=9:antialias=true",
		"Font Awesome 5 Brands Regular:size=9:antialias=true",
		"DejaVu Serif:size=8:antialias=true",
	]
	# General settings
	loggingEnabled = false

[monitors]
	[monitors.default.tags]
		1.displayString = "!"
		2.displayString = "@"
		3.displayString = "#"
		4.displayString = "$"
		5.displayString = "%"
		6.displayString = "^"
		7.displayString = "&"
		8.displayString = "*"
		9.displayString = "~"
