#!/bin/sh

start() {
	if [ -z "$1" ]; then
		return 1
	fi

	$1 &
}

start_once() {
	if [ -z "$1" ]; then
		return 1
	fi

	if [ ! "$(ps aux | grep "$1" | sed '$ d' | head -n 1 | awk -v usr="$USER" '{if ($1 == usr) { print $1 }}')" = "$USER" ]; then
		$1 &
	fi
}

# colours
CL_NORMAL_BORDER="#7197E7"
CL_ACTIVE_BORDER="$CL_NORMAL_BORDER"
CL_FOCUSED_BORDER="#A77AC4"
CL_PRESEL_FEEDBACK="$CL_FOCUSED_BORDER"
CL_URGENT_BORDER="#E14C4F"

# in case bspwm was restarted, reset rules
bspc rule -r "*"

# desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20

# pointer modifier
bspc config pointer_modifier mod4

# border colours
bspc config normal_border_color "$CL_NORMAL_BORDER"
bspc config active_border_color "$CL_ACTIVE_BORDER"
bspc config focused_border_color "$CL_FOCUSED_BORDER"
bspc config presel_feedback_color "$CL_PRESEL_FEEDBACK"
bspc config urgent_border_color "$CL_URGENT_BORDER"

# border width
bspc config border_width 2

# window gap
bspc config window_gap 7

# window padding
bspc config top_padding 17 # the same as polybar height
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

# split ratio
bspc config split_ratio 0.5

# focus follows a pointer
bspc config focus_follows_pointer true

# pointer does not follow focus
bpsc config pointer_follows_focus false

# pointer des not follow a monitor
bspc config pointer_follows_monitor false

# disable ewmh focus
bspc config ignore_ewmh_focus true

# application rules
bspc rule -a firefox desktop=^1
bspc rule -a discord desktop=^2 follow=off
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Spotify desktop=^4
bspc rule -a "Gimp-2.10" desktop=^5
bspc rule -a obs desktop=^6
bspc rule -a VSCodium desktop=^8
bpsc rule -a "VirtualBox Manager" desktop=^9
bspc rule -a "VirtualBox Machine" desktop=^10
bspc rule -a "*:Steam - News" state=floating rectangle=800x600

# autostart

# sxhkd
pkill sxhkd
wait $!
start sxhkd
start "sxhkd -c $CONFIG/sxhkd/bspwm"

# polybar
start "$CONFIG/polybar/launch.sh bspwm"

# picom
start_once "picom -cC"

# unclutter
start_once unclutter

# numlockx
start_once "numlockx on"

# wallpaper
start "go run $SCRIPTS/wallpapers.go"

# apps
start_once firefox
start_once discord
start_once telegram-desktop
start_once spotify

# vim:ft=sh
