#!/bin/bash
FIFO="/tmp/s_dnd_pipe"

[ ! -e "$FIFO" ] && touch "$FIFO"

case "$1" in
	"dnd")
		echo "dnd" > "$FIFO"
		dunstify -t 200 "you've enabled DND mode"
		exit 0
		;;
	"free")
		echo "free" > "$FIFO"
		dunstify "you've enabled notifications"
		exit 0
		;;
esac

pidof -o %PPID -x "$0" >/dev/null && exit 0

echo "free" > "$FIFO"

while true; do
	case "$(cat "$FIFO")" in
		"dnd")
			echo "DND"
			dunstify DUNST_COMMAND_PAUSE
			;;
		"free")
			echo "free"
			dunstify DUNST_COMMAND_RESUME
			;;
	esac
	sleep 1s
done
