#!/bin/bash

FIFO="/tmp/s_dnd_pipe"

[ ! -e "$FIFO" ] && touch "$FIFO"

free(){
	echo "free" > "$FIFO"
}

dnd(){
	echo "dnd" > "$FIFO"
}

case "$1" in
	"dnd")
		dnd
		dunstify -t 300 "you've enabled DND mode"
		exit 0
		;;
	"free")
		free
		dunstify "you've enabled notifications"
		exit 0
		;;
esac

pidof -o %PPID -x "$0" >/dev/null && exit 0

free

fs_detect(){
	win="$(xdotool getactivewindow)"
	[ ! $? -eq 0 ] && free && return 0

	xprop -id "$win" | grep -q _NET_WM_STATE_FULLSCREEN && dnd || free
}

while true; do
	case "$(cat "$FIFO")" in
		"dnd")
			echo "DND"
			dunstctl set-paused true
			;;
		"free")
			echo "free"
			dunstctl set-paused false
			;;
	esac

	fs_detect

	sleep 1s
done
