#!/bin/bash

source "$SCRIPTS/s_colours.sh"

while true; do
	UNREAD="$(gh api notifications | jq length)"
	if [[ "$UNREAD" -eq 0 ]]; then
		echo " $UNREAD"
	else
		echo "${FG_RED} ${UNREAD}${FG_NORMAL}"
	fi
	sleep 1m
done
