#!/bin/bash

source "$SCRIPTS/s_colours.sh"

while true; do
	UNREAD="$(gh api notifications | jq length)"
	[[ -z $LAST_COUNT ]] && LAST_COUNT=$UNREAD
	if [[ "$UNREAD" -eq 0 ]]; then
		echo " $UNREAD"
		LAST_COUNT=0
	else
		if [[ $UNREAD -gt $LAST_COUNT ]]; then
			DIFF=$((UNREAD-LAST_COUNT))
			case "$DIFF" in
				1)
					dunstify -a 'GitHub' "You've got an unread notification"
					;;
				*)
					dunstify -a 'GitHub' "You've got $DIFF unread notifications"
					;;
			esac
		fi
		echo "${FG_RED} ${UNREAD}${FG_NORMAL}"
		LAST_COUNT=$UNREAD
	fi
	sleep 1m
done
