#!/bin/sh

LAYOUTS="$(setxkbmap -query | awk 'FNR == 3 { print $2 }')"
INDEX="$(xset -q | awk 'FNR == 2 { print $NF }')"
INDEX="${INDEX#????}"
INDEX="${INDEX%???}"

CUR="$(echo "$LAYOUTS" | cut -d ',' --fields=$((INDEX+1)))"

echo "  $CUR"

while true; do
	CUR="$(echo "$LAYOUTS" | cut -d ',' --fields=$((INDEX+1)))"
	while true; do
		INDEX="$(xset -q | awk 'FNR == 2 { print $NF }')"
		INDEX="${INDEX#????}"
		INDEX="${INDEX%???}"
		[ ! "$(echo "$LAYOUTS" | cut -d ',' --fields=$((INDEX+1)))" = "$CUR" ] && break
	done
	INDEX="$(xset -q | awk 'FNR == 2 { print $NF }')"
	INDEX="${INDEX#????}"
	INDEX="${INDEX%???}"
	CUR="$(echo "$LAYOUTS" | cut -d ',' --fields=$((INDEX+1)))"
	echo "  $CUR"
done
