#!/bin/sh

#
#	This file is part of nimdowstatus program
#	Made by Lasha Kanteladze, a.k.a dakyskye
#	Licensed under the MIT license
#	Repository: https://github.com/dakyskye/nimdowstatus
#

echo "$(uname -r | cut -d '-' -f 1)"
