#!/bin/bash

source "$SCRIPTS/s_colours.sh"

while true; do
	USAGE="$(free -t | awk 'FNR == 2 {print $3/$2*100}' | cut -d '.' -f1)"

	if [[ "$USAGE" -lt 41 ]]; then
		echo " ${USAGE}%${FG_NORMAL}"
	elif [[ "$USAGE" -gt 40 && "$USAGE" -lt 61 ]]; then
		echo "${FG_YELLOW} ${USAGE}%${FG_NORMAL}"
	elif [[ "$USAGE" -gt 60 ]]; then
		echo "${FG_RED} ${USAGE}%${FG_NORMAL}"
	fi
	sleep 1
done
