#!/bin/sh

#
#	This file is part of nimdowstatus program
#	Made by Lasha Kanteladze, a.k.a dakyskye
#	Licensed under the MIT license
#	Repository: https://github.com/dakyskye/nimdowstatus
#

while true; do
	echo "$(free -t | awk 'FNR == 2 {print $3/$2*100}' | cut -d '.' -f1)"
	sleep 1
done
