#!/bin/sh

trap "exit" INT TERM HUP
trap "kill 0" EXIT

cpu() {
	T_CPU="C $(sensors | grep -A 8 k10temp-pci | awk '{ if ($1 == "Tdie:") { print $2 } }' | sed -nE 's/\+([0-9][0-9])\..*/\1/p')"
}

gpu() {
	T_GPU="G $(sensors | grep -A 6 amdgpu-pci | awk '{ if ($1 == "edge:") { print $2 } }' | sed -nE 's/\+([0-9]+)\..*/\1/p')"
}

hdd() {
	T_HDD="H $(echo $(nc 127.0.0.1 7634) | sed -nE 's/.*SAMSUNG.*?\|([0-9]+)\|.*/\1/p')"
}

ssd() {
	T_SSD="S $(echo $(nc 127.0.0.1 7635) | sed -nE 's/.*KINGSTON.*?\|([0-9]+)\|.*/\1/p')"
}


while true; do
	cpu 
	gpu 
	hdd 
	ssd 
	sleep 0.5
	echo " ${T_CPU}°C |  ${T_GPU}°C |  ${T_HDD}°C |  ${T_SSD}°C"
	sleep 2
done
