#!/bin/bash

source "$SCRIPTS/s_colours.sh"

trap "exit" INT TERM HUP
trap "kill 0" EXIT

ICOT=""
ICOC="°C"

cpu() {
	CTEMP="$(sensors | grep -A 8 k10temp-pci | awk '{ if ($1 == "Tdie:") { print $2 } }' | sed -nE 's/\+([0-9][0-9])\..*/\1/p')"
	T_CPU="C ${ICOT} ${CTEMP}${ICOC}"
	if [[ "$CTEMP" -gt 45 && "$CTEMP" -lt 71 ]]; then
		T_CPU="${FG_YELLOW}${T_CPU}${FG_NORMAL}"
	elif [[ "$CTEMP" -gt 70 ]]; then
		T_CPU="${FG_RED}${T_CPU}${FG_NORMAL}"
	fi
}

gpu() {
	GTEMP="$(sensors | grep -A 6 amdgpu-pci | awk '{ if ($1 == "edge:") { print $2 } }' | sed -nE 's/\+([0-9]+)\..*/\1/p')"
	T_GPU="G ${ICOT} ${GTEMP}${ICOC}"
	if [[ "$GTEMP" -gt 45 && "$GTEMP" -lt 71 ]]; then
		T_GPU="${FG_YELLOW}${T_GPU}${FG_NORMAL}"
	elif [[ "$GTEMP" -gt 70 ]]; then
		T_GPU="${FG_RED}${T_GPU}${FG_NORMAL}"
	fi
}

hdd() {
	HTEMP="$(sensors | grep -A 4 drivetemp-scsi-1-0 | awk '{ if ($1 == "temp1:") { print $2 } }' | sed -nE 's/\+([0-9]+)\..*/\1/p')"
	T_HDD="H ${ICOT} ${HTEMP}${ICOC}"
	if [[ "$HTEMP" -gt 35 && "$HTEMP" -lt 51 ]]; then
		T_HDD="${FG_YELLOW}${T_HDD}${FG_NORMAL}"
	elif [[ "$HTEMP" -gt 50 ]]; then
		T_HDD="${FG_RED}${T_HDD}${FG_NORMAL}"
	fi
}

ssd() {
	STEMP="$(sensors | grep -A 4 drivetemp-scsi-0-0 | awk '{ if ($1 == "temp1:") { print $2 } }' | sed -nE 's/\+([0-9]+)\..*/\1/p')"
	T_SSD="S ${ICOT} ${STEMP}${ICOC}"
	if [[ "$STEMP" -gt 40 && "$STEMP" -lt 51 ]]; then
		T_SSD="${FG_YELLOW}${T_SSD}${FG_NORMAL}"
	elif [[ "$STEMP" -gt 50 ]]; then
		T_SSD="${FG_RED}${T_SSD}${FG_NORMAL}"
	fi
}

while true; do
	cpu
	gpu
	hdd
	ssd
	sleep 0.5
	echo "${T_CPU} | ${T_GPU} | ${T_HDD} | ${T_SSD}"
	sleep 2
done
