#!/bin/bash

source "$SCRIPTS/s_colours.sh"

printupdates() {
	UPDATES="$(pacman -Qu | wc -l)"
	if [[ "$UPDATES" -gt 0 ]]; then
		echo "${FG_RED} ${UPDATES}${FG_NORMAL}"
	else
		echo " $UPDATES"
	fi
}

echo " updating"
sleep 10
printupdates

while true; do
	sleep 1m
	printupdates
done
