#!/bin/bash

source "$SCRIPTS/s_colours.sh"

printupdates() {
	UPDATES="$(EIX_LIMIT=1 eix --installed --upgrade | grep '^Found' | awk '{ print $2; }')"
	if [[ "$UPDATES" -gt 0 ]]; then
		echo "${FG_RED} ${UPDATES}${FG_NORMAL}"
	else
		echo " 0"
	fi
}

while true; do
	printupdates
	sleep 10m
done
