#!/bin/sh

print_vol() {
	VOL="$(pamixer --get-volume)"
	[ "$(pamixer --get-mute)" = "true" ] && echo "  ${VOL}" || echo "  ${VOL}"
}

print_vol

pactl subscribe | while read -r LINE; do
	echo "$LINE" | grep -qv "client" && print_vol
done
