#!/bin/bash

source "$SCRIPTS/s_colours.sh"

print_vol() {
	PA_SINK="$(pacmd info | grep "Default sink name:" | awk '{ print $4; }')"
	SINK_INFO="$(pactl list sinks | grep -m1 -A 8 $PA_SINK)"

	VOL="$(echo "$SINK_INFO" | grep "Volume:" | awk '{ print $5; }')"
	VOL=${VOL%?}
	[[ "$(echo "$SINK_INFO" | grep "Mute:" | awk '{ print $2; }')" = "yes" ]] && VOL=" $VOL" || VOL=" $VOL"
	
	if [[ "${VOL#??}" -lt 66 ]]; then
		echo "${VOL}${FG_NORMAL}"
	elif [[ "${VOL#??}" -gt 65 && "${VOL#??}" -lt 86 ]]; then
		echo "${FG_YELLOW}${VOL}${FG_NORMAL}"
	elif [[ "${VOL#??}" -gt 85 ]]; then
		echo "${FG_RED}${VOL}${FG_NORMAL}"
	fi
}

print_vol

pactl subscribe | while read -r LINE; do
	echo "$LINE" | grep -qv "client" && print_vol
done
