#!/bin/sh

TMPOUT=$(mktemp)
TMPFILE=$(mktemp --suffix ".png")
TMPMAGICK=$(mktemp --suffix ".png")

trap 'rm -f "$TMPOUT" "$TMPFILE" "$TMPMAGICK"' EXIT

SS_PATH="$HOME/Images/screenshots"
SS_FORMAT="$SS_PATH/screenshot_$(date '+%d.%m.%Y_%H.%M.%S').png"
NOTIFY_COPY="the screenshot has been taken and copied to your clipboard"
NOTIFY_SAVE="the screenshot has been taken and saved locally at $SS_PATH"
NOTIFY_UPLOAD="the link of captured screenshot has been copied to your clipboard"
NOTIFY_APP_NAME="scr"

FC="fc"
WC="wc"
WCB="wcb"
FS="fs"
WS="ws"
WSB="wsb"
FU="fu"
WU="wu"
WUB="wub"

maimscr() {
	maim $1 "${2:-$TMPFILE}" > "$TMPOUT" 2>&1

	case "$(cat "$TMPOUT")" in "") return 0; esac

	return 1
}

magickback() {
	[ -z "$1" ] && return 1

	SIZE="$(identify -format '%w %h' "$1")"
	WIDTH="${SIZE% *}"
	HEIGHT="${SIZE#* }"
	convert -size "$(($WIDTH+40))"x"$(($HEIGHT+40))" canvas:white "$TMPMAGICK"
	convert "$TMPMAGICK" -colorspace sRGB -gravity center "$1" -composite "$1"
}

screenshot() {
	[ -z "$1" ] && return 1

	case "$1" in
		"$FC")
			maimscr && xclip -selection clipboard -t image/png -i "$TMPFILE" && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_COPY"
			;;
		"$WC")
			maimscr "-sou" && xclip -selection clipboard -t image/png -i "$TMPFILE" && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_COPY"
			;;
		"$WCB")
			maimscr "-sou" && magickback "$TMPFILE" && xclip -selection clipboard -t image/png -i "$TMPFILE" && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_COPY"
			;;
		"$FS")
			maimscr "" "$SS_FORMAT" && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_SAVE"
			;;
		"$WS")
			maimscr "-sou" "$SS_FORMAT" && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_SAVE"
			;;
		"$WSB")
			maimscr "-sou" "$SS_FORMAT" && magickback "$SS_FORMAT" && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_SAVE"
			;;
		"$FU")
			maimscr && 0x0 "$TMPFILE" | xclip -selection clipboard && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_UPLOAD"
			;;
		"$WU")
			maimscr "-so" && 0x0 "$TMPFILE" | xclip -selection clipboard && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_UPLOAD"
			;;
		"$WUB")
			maimscr "-so" && magickback "$TMPFILE" && 0x0 "$TMPFILE" | xclip -selection clipboard && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_UPLOAD"
			;;
	esac
}

if [ -n "$1" ]; then
	screenshot "$1"
else
	CHOICE=$(printf "1) fullscreen and copy\n2) select a window and copy\n3) select a window and copy (b)\n4) fullscreen and save\n5) select a window and save\n6) select a window and save (b)\n7) fullscreen and upload to 0x0\n8) select a window and upload to 0x0\n9) select a window and upload to 0x0 (b)" | rofi -dmenu -p "make the choice")

	sleep 0.3

	case "$CHOICE" in
		"1)"*)
			screenshot "$FC"
			;;
		"2)"*)
			screenshot "$WC"
			;;
		"3)"*)
			screenshot "$WCB"
			;;
		"4)"*)
			screenshot "$FS"
			;;
		"5)"*)
			screenshot "$WS"
			;;
		"6)"*)
			screenshot "$WSB"
			;;
		"7)"*)
			screenshot "$FU"
			;;
		"8)"*)
			screenshot "$WU"
			;;
		"9)"*)
			screenshot "$WUB"
			;;
	esac
fi
