#!/bin/sh

TMPOUT=$(mktemp)
TMPFILE=$(mktemp)
mv "$TMPFILE" "$TMPFILE.png"
TMPFILE="$TMPFILE.png"

trap 'rm -f "$TMPOUT" "$TMPFILE"' EXIT

SS_PATH="$HOME/Images/screenshots"
SS_FORMAT="$SS_PATH/screenshot_$(date '+%d.%m.%Y_%H.%M.%S').png"
NOTIFY_COPY="the screenshot has been taken and copied to your clipboard"
NOTIFY_SAVE="the screenshot has been taken and saved locally at $SS_PATH"
NOTIFY_UPLOAD="the link of captured screenshot has been copied to your clipboard"
NOTIFY_APP_NAME="scr"

FC="fc"
WC="wc"
FS="fs"
WS="ws"
FU="fu"
WU="wu"

maimscr() {
	echo "$TMPFILE"
	maim $1 "${2:-$TMPFILE}" > "$TMPOUT" 2>&1

	case "$(cat "$TMPOUT")" in "") return 0; esac

	return 1
}

screenshot() {
	[ -z "$1" ] && return 1

	case "$1" in
		"$FC")
			maimscr && xclip -selection clipboard -t image/png -i "$TMPFILE" && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_COPY"
			;;
		"$WC")
			maimscr "-sou" && xclip -selection clipboard -t image/png -i "$TMPFILE" && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_COPY"
			;;
		"$FS")
			maimscr "" "$SS_FORMAT" && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_SAVE"
			;;
		"$WS")
			maimscr "-sou" "$SS_FORMAT" && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_SAVE"
			;;
		"$FU")
			maimscr && 0x0 "$TMPFILE" | xclip -selection clipboard && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_UPLOAD"
			;;
		"$WU")
			maimscr "-so" && 0x0 "$TMPFILE" | xclip -selection clipboard && notify-send -a "$NOTIFY_APP_NAME" "$NOTIFY_UPLOAD"
			;;
	esac
}

if [ -n "$1" ]; then
	screenshot "$1"
else
	CHOICE=$(printf "1) fullscreen and copy\n2) select a window and copy\n3) fullscreen and save\n4) select a window and save\n5) fullscreen and upload to 0x0\n6) select a window and upload to 0x0" | rofi -dmenu -p "make the choice")

	sleep 0.3

	case "$CHOICE" in
		"1)"*)
			screenshot "$FC"
			;;
		"2)"*)
			screenshot "$WC"
			;;
		"3)"*)
			screenshot "$FS"
			;;
		"4)"*)
			screenshot "$WS"
			;;
		"5)"*)
			screenshot "$FU"
			;;
		"6)"*)
			screenshot "$WU"
			;;
	esac
fi
