#!/bin/sh

N="night mode"
D="day mode"

NOTIFY_APP_NAME="screen warmness"

warmness() {
	[ -z "$1" ] && return 1

	case "$1" in
		"$N"|"n")
			redshift -P -O 4500 && dunstify -a "$NOTIFY_APP_NAME" "enabled $N"
			;;
		"$D"|"d")
			redshift -P -O 6500 && dunstify -a "$NOTIFY_APP_NAME" "enabled $D"
			;;
	esac
}

if [ -n "$1" ]; then
	warmness "$1"
else
	CHOICE=$(printf "$N\n$D" | rofi -dmenu -p "make the choice")

	case "$CHOICE" in
		"$N")
			warmness "$N"
			;;
		"$D")
			warmness "$D"
			;;
	esac
fi
