#!/bin/sh

case "$1" in
	on)
		xrandr --output HDMI-A-0 --primary --mode 1920x1080 --pos 1360x0 --rotate normal --output DisplayPort-0 --off --output DisplayPort-1 --off --output HDMI-A-1 --mode 1360x768 --pos 0x0 --rotate normal --output DVI-D-0 --off
		;;
	off)
		xrandr --output HDMI-A-0 --primary --mode 1920x1080 --pos 1360x0 --rotate normal --output DisplayPort-0 --off --output DisplayPort-1 --off --output HDMI-A-1 --off --output DVI-D-0 --off
		;;
esac
