#!/bin/sh

POWEROFF="poweroff"
REBOOT="reboot"
SUSPEND="suspend"
HIBERNATE="hibernate"
HYBRID_SLEEP="hybrid-sleep"
LOGOUT="log out"
LOCK="lock"

operation() {
	[ -z "$1" ] && return 1

	case "$1" in
		"$POWEROFF")
			loginctl "$POWEROFF"
			;;
		"$REBOOT")
			loginctl "$REBOOT"
			;;
		"$SUSPEND")
			#systemctl "$SUSPEND"
			;;
		"$HIBERNATE")
			#systemctl "$HIBERNATE"
			;;
		"$HYBRID_SLEEP")
			#systemctl "$HYBRID_SLEEP"
			;;
		"$LOGOUT")
			loginctl kill-user $USER
			;;
		"$LOCK")
			[ "$(playerctl status)" = "Playing" ] && WAS_AUDIO_PLAYING=0
			playerctl pause
			pactl set-sink-mute @DEFAULT_SINK@ 1
			dunstctl set-paused true

			tmpdir=$(mktemp -d)
			original="$tmpdir/original.png"
			blurred="$tmpdir/blurred.png"

			[ "$2" = "menu" ] && sleep 0.5

			maim -ou "$original"
			convert "$original" -blur 0x6 "$blurred"
			i3lock -n -e -f -i "$blurred"
			rm -rf "$tmpdir"

			[ $WAS_AUDIO_PLAYING ] && playerctl play
			pactl set-sink-mute @DEFAULT_SINK@ 0
			dunstctl set-paused false
			dunstify "welcome back!"
			;;
	esac
}

if [ -n "$1" ]; then
	operation "$1"
else
	CHOICE=$(printf "$POWEROFF\n$REBOOT\n$SUSPEND\n$HIBERNATE\n$HYBRID_SLEEP\n$LOGOUT\n$LOCK" | rofi -dmenu -p "make the choice")

	operation "$CHOICE" "menu"
fi
