#!/bin/sh

operation() {
	[ -z "$1" ] && return 1

	case "$1" in
		shutdown)
			systemctl poweroff
			;;
		reboot)
			systemctl reboot
			;;
		suspend)
			systemctl suspend
			;;
		hibernate)
			systemctl hibernate
			;;
		hybrid-sleep)
			systemctl hybrid-sleep
			;;
		logout)
			pkill -9 -U $USER
			;;
		lock)
			notify-send DUNST_COMMAND_PAUSE
			tmpdir=$(mktemp -d)
			original="$tmpdir/original.png"
			blurred="$tmpdir/blurred.png"
			sleep 0.3
			maim -ou "$original"
			convert "$original" -blur 0x5 "$blurred"
			i3lock -n -e -f -i "$blurred"
			rm -rf "$tmpdir"
			notify-send DUNST_COMMAND_RESUME
			notify-send "welcome back!"
			;;
	esac
}

if [ -n "$1" ]; then
	operation "$1"
else
	CHOICE=$(printf "1) power off\n2) reboot\n3) hibernate\n4) suspend\n5) hybrid sleep\n6) log out\n7) lock" | rofi -dmenu -p "make the choice")

	case "$CHOICE" in
		"1)"*)
			operation shutdown
			;;
		"2)"*)
			operation reboot
			;;
		"3)"*)
			operation hibernate
			;;
		"4)"*)
			operation suspend
			;;
		"5)"*)
			operation hybrid-sleep
			;;
		"6)"*)
			operation logout
			;;
		"7)"*)
			operation lock
			;;
	esac
fi

# vim: ft=sh
