#!/bin/sh

POWEROFF="poweroff"
REBOOT="reboot"
SUSPEND="suspend"
LOGOUT="log out"
LOCK="lock"

operation() {
	[ -z "$1" ] && return 1

	case "$1" in
		"$POWEROFF")
			loginctl "$POWEROFF"
			;;
		"$REBOOT")
			loginctl "$REBOOT"
			;;
		"$SUSPEND")
			loginctl "$SUSPEND"
			;;
		"$LOGOUT")
			loginctl kill-user "$USER"
			;;
		"$LOCK")
			KEEPAUDIO=$(printf "no\nyes" | rofi -dmenu -p "do you want to keep audio playing?")
			case "$KEEPAUDIO" in
				yes)
					;;
				*)
					[ "$(playerctl status)" = "Playing" ] && WAS_AUDIO_PLAYING=0
					playerctl pause
					pactl set-sink-mute @DEFAULT_SINK@ 1
					;;
			esac

			dunstify "DUNST_COMMAND_PAUSE"

			tmpdir=$(mktemp -d)
			original="$tmpdir/original.png"
			blurred="$tmpdir/blurred.png"

			[ "$2" = "menu" ] && sleep 0.5

			maim -ou "$original"
			convert "$original" -blur 0x6 "$blurred"
			i3lock -n -e -f -i "$blurred"
			rm -rf "$tmpdir"

			case "$KEEPAUDIO" in
				yes)
					;;
				*)
					[ $WAS_AUDIO_PLAYING ] && playerctl play
					pactl set-sink-mute @DEFAULT_SINK@ 0
					;;
			esac

			[ ! "$(cat /tmp/s_dnd_pipe 2>/dev/null)" = "dnd" ] && dunstify "DUNST_COMMAND_RESUME"
			dunstify "welcome back!"
			;;
	esac
}

if [ -n "$1" ]; then
	operation "$1"
else
	# shellcheck disable=SC2059
	CHOICE=$(printf "$POWEROFF\n$REBOOT\n$SUSPEND\n$LOGOUT\n$LOCK" | rofi -dmenu -p "make the choice")

	operation "$CHOICE" "menu"
fi
